linuxdeepin/dde-session-ui

- session-widgets/userinfo.cpp
The file /usr/share/backgrounds/deepin/desktop.jpg is abandoned.
> chore(ADDomain): update default wallpaper

- session-widgets/lockworker.cpp
- session-widgets/lockworker.h
greeter启动后会进入认证状态，如果使用的是指纹验证，并不会调用，因为需要手动调用一下greeter的respond方法。
TODO： 当用户A使用指纹时进行用户切换，认证失败的提示将会显示在用户B这里，考虑以后把错误信息封装在User类中，这样LockContent和UserInputWidget可以根据用户来显示错误。
> fix(greeter): mulit-user fingerprint login

- dde-shutdown/view/contentwidget.cpp
- dde-shutdown/view/contentwidget.h
现在dde-shutdown是后台常驻，再次显示出来会非常快，通过命令行调用会导致界面收到了松开按键的事件。
> refactor(Shutdown): change keyReleaseEvent to keyPressEvent

- libdde-auth/deepinauthframework.cpp
- session-widgets/lockworker.cpp
- session-widgets/lockworker.h
- session-widgets/sessionbasemodel.cpp
- session-widgets/userinfo.cpp
- session-widgets/userinfo.h
- session-widgets/userinputwidget.cpp
- session-widgets/userinputwidget.h
移动用户的nopasswordgrp到函数返回时检查，因为锁屏不再退出了，而无密码登录的设置是立即生效的。
将空密码检查放在userinput那里处理。
> 修复无密码登录无法解锁

- session-widgets/lockworker.cpp
解锁失败的情况下不能关闭验证过程，否则指纹设备将在第一次认证失败就被关闭。
> fix(lock): shutdown fprintd device for the first time

- session-widgets/lockworker.cpp
> fix(lock): can always auth user

- session-widgets/lockworker.cpp
为了启用指纹登录，会启动时调用验证，但是会导致收到一个验证失败，需要处理一下。
> fix(greeter): Prevent failures caused by authentication at startup

- session-widgets/userinputwidget.cpp
Without the fix, lightdm-deepin-greeter always crashes when starting up
for the first time on each boot.
> fix: crash in refreshInputState when m_user is null

- dde-shutdown/view/systemmonitor.cpp
> fix (dde-shutdown): system monitor button text overflow.

- lightdm-deepin-greeter/loginwindow.cpp
- session-widgets/lockworker.cpp
禁用动画的情况下，控件和壁纸都来不及绘制，lightdm-deepin-greeter就被杀掉了，导致X上残留了一些画面，这个提交会优化这个情况
> optimize(greeter): forced to draw wallpaper

- dde-lock/lockworker.cpp
- session-widgets/userinputwidget.cpp
ignore nopasslogin group of users in dde-lock
because unlock is not login
> refactor: alway authenticate user on lock application

- dde-shutdown/view/contentwidget.cpp
- dde-shutdown/view/contentwidget.h
- dde-shutdown/view/inhibitwarnview.cpp
- dde-shutdown/view/inhibitwarnview.h
PMS taskID=6259
之前检查应用商店的地方改成了检查所有试图阻止关机的应用，并列表显示这些应用。
和新设计有一些冲突所以这个提交没严格按照设计图来做。冲突的地方是：
1. 没有关机按钮，只能取消。
2. 只显示所有试图阻止（block）关机的项，没有显示允许延缓的项。
3. 无法获得阻止关机的应用程序的图标。
1 的原因是之前只检查商店的情况就没有，并且 block 关机的情况就是要阻止关机。2 是这次提交只打算支持 block 阻止关机，如果确定要支持 delay 的话可以细分到别的提交来做。另外是，如果 delay 的话，是要发送  `PrepareForShutdown()` / `PrepareForSleep()` dbus 信号用来通知程序的（比如程序收到信号后做保存文件之类的行为），这个信号由谁来发我还没仔细研究。3 是因为 `Inhibit()` 只提供了应用名称和应用阻止关机行为的原因这两个参数（另外两个参数是阻止模式 block/delay 和阻止什么行为 shutdown/logout/etc）。
> feat: list all inhibitors

- .packit.yaml
- rpm/dde-session-ui.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> feat: Initial packit setup

- archlinux/PKGBUILD
- debian/changelog
cmake --install . --prefix will override -DCMAKE_INSTALL_PREFIX
> fix: install prefix not effective

- debian/control
更新依赖描述（libxcb-util0 -> libxcb-util1），使可以在新版 debian 中顺利构建。（注：在 v20 停止支持后，可考虑移除 libxcb-util0 依赖）
是处理 linuxdeepin/developer-center#3230 问题的一部分。
Log: build on new debian release
Influence: build
Change-Id: Ie9ef716c2190fed9f2583fcc84553534113b45ad
> chore: build on newer debian release

- dde-osd/notification/bubble.cpp
添加WindowDoesNotAcceptFocus窗口属性
Log: 锁屏时通知窗口获得焦点，打断当前焦点输入
Bug: https://pms.uniontech.com/bug-view-155551.html
Influence: 锁屏时弹出通知窗口，不会触发焦点切换，不会影响当前正在进行的业务流程
Change-Id: Idda0bc0fecedb10235cde3494a8b4facdb59a6f8
> fix: 锁屏时通知窗口获得焦点，打断当前焦点输入

- dde-osd/container.cpp
原因:锁屏层级为onScreenDisplay,osd的层级为tooltip
解决方案: osd提示的层级提高到onScreenDisplay
Log: 修复wayland下锁屏不显示OSD提示的问题
Bug: https://pms.uniontech.com/bug-view-155345.html
Influence: wayland锁屏OSD弹窗
Change-Id: I9136a8bd321b8986c3c31a49dc5f673efe320213
> fix: wayland下锁屏不显示OSD

- CMakeLists.txt
- dde-osd/files/com.deepin.dde.Notification.service
- dde-osd/files/com.deepin.dde.freedesktop.Notification.service
- dde-osd/files/com.deepin.dde.osd.service
- dde-osd/files/dde-osd.desktop
根因:systemd方式启动的进程没有正确获取环境变量，界面透明效果异常
修复:修改dde-osd程序启动方式，通过StartManager.Launch启动desktop文件方式启动进程，以继承环境变量
Log: 修复通知中心的毛玻璃蒙层效果丢失的问题
Bug: https://pms.uniontech.com/bug-view-155485.html
Influence: 正常显示界面效果
> fix: 修改dde-osd程序启动方式

- dde-osd/container.cpp
osd窗口属性由Qt::ToolTip改为Tool，ToolTip一般用于QToolTip的实现，
工具型的窗口应该用Qt::Tool，且在使用ToolTip时，会导致此问题
Log: 修复部分情况下osd不显示的问题
Influence: 通知消失的时候弹出osd会不显示(需要频繁按出osd)
Bug: https://pms.uniontech.com/bug-view-156715.html
Change-Id: If70a28b5c756d7d98d59cb399c395b723104d494
> fix: 修复部分情况下osd不显示的问题

- dde-lowpower/window.cpp
低电量待机后唤醒，显示的是锁屏而不是低电量提醒界面，原因是低电量提示界面层级笔锁屏要低，需要将层级提高为override
Log: 修复低电量界面和锁屏交互异常的问题
Bug: https://pms.uniontech.com/bug-view-157769.html
Influence: 低电量提醒
Change-Id: I85df852092173a0f85d6d53253265166fdb8df0b
> fix: 低电量界面和锁屏交互异常

- dde-osd/manager.cpp
非激活session下的osd会对请求进行响应
判断session是否激活,非激活不响应
Log: 对osd请求进行优化
Bug: https://pms.uniontech.com/bug-view-153133.html
Influence: osd弹框
> fix: 修复A用户启用或禁用触摸板,进入B用户登录页面,会自动弹出osd弹窗问题

- dde-bluetooth-dialog/main.cpp
1.蓝牙弹窗参数可以为3个，保证兼容旧版本dde-daemon;
2.第四个参数为"true"或"false"的字符串;
Log: 修正蓝牙弹窗参数个数的校正和入参处理
Bug: https://pms.uniontech.com/bug-view-160137.html
Influence: 蓝牙连接
Change-Id: I501f903afaf0c10894304888da57ccb904841e82
> fix: 修正蓝牙弹窗参数个数的校正和入参处理

- README.md
- README.zh_CN.md
The protocol name in the README is written according to the standard specification
Log: modify README license information
Influence: none
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: Ief84871581f57509f55b43b87c56e943d9211e68
> chore: modify README license information

- dde-osd/manager.cpp
上一个OSD没有隐藏时，显示下一个OSD时没有调整界面大小，会使用上一个界面的尺寸，造成界面显示不全
Log: 修复F1-F9热键，第二个OSD窗口会记录第一个OSD窗口大小的问题
Bug: https://pms.uniontech.com/bug-view-161429.html
Influence: 使用F1-F9功能按键时正常显示OSD
> fix: 显示不同类型OSD时需要重新调整界面大小

- .reuse/dep5
- dde-welcome/utils.cpp
根据os-version去读取对应的版本信息，防止显示的版本信息错误
Log: 修复社区版登录桌面时版本提示信息错误的问题
Bug: https://pms.uniontech.com/bug-view-137439.html
Influence: 登录界面版本提示信息
Change-Id: I8338e51a0cc2706507c59270a048a9f447ac34af
> fix: 社区版登录桌面时版本提示信息错误

- dde-osd/files/com.deepin.dde.Notification.service
- dde-osd/files/com.deepin.dde.freedesktop.Notification.service
- dde-osd/files/com.deepin.dde.osd.service
由于社区缺少qdbus工具，改用dbus-send命令
Log: 修复待机休眠后osd无法显示问题
Bug: https://pms.uniontech.com/bug-view-161737.html
Influence: osd显示
Change-Id: I7812edcb647742ef7152baf211a57daa5cb426d1
> fix: 修复待机休眠后osd无法显示问题

- dde-osd/notification-center/notifycenterwidget.cpp
多屏开缩放的情况下，qt获取的坐标有问题，需要重新计算
Log: 修复通知中心鼠标点击或滚轮滚动都会导致隐藏的问题
Bug: https://pms.uniontech.com/bug-view-163961.html
Influence: 通知中心
Change-Id: I2022d112191b9f878d7f9192b29b28f547ead853
> fix: 修复通知中心鼠标点击或滚轮滚动都会导致隐藏的问题

- dde-osd/container.cpp
需要根据X11或wayland分别设置窗口属性
Log: 修复在字体字号设置为20后，窗口特效开关OSD提示界面显示不完整的问题
Bug: https://pms.uniontech.com/bug-view-164657.html
Influence: 窗口特效开关OSD提示界面正常显示
> fix: 需要根据X11或wayland分别设置窗口属性

- dde-osd/notification-center/itemdelegate.cpp
- dde-osd/notification-center/notifycenterwidget.cpp
根据UI设计要求，调整消息通知主标题和消息通知列表间距为20,调整消息通知应用标题和消息通知内容间距为6
Log: 修复标题与内容间距问题
Bug: https://pms.uniontech.com/bug-view-167541.html
Influence: 标题与内容间距按要求显示
> fix: 根据UI设计要求调整标题间距

- dde-osd/notification-center/notifycenterwidget.cpp
- dde-osd/notification/iconbutton.cpp
1、在鼠标离开按钮时需要清除焦点，否则会一直显示 hover状态颜色
2、修改按钮焦点策略，否则启动时就会获得焦点显示 hover状态颜
3、判断状态条件不对，无法区分点击和悬浮状态，会一直显示 hover状态颜色
Log: 修复消息中心清除按钮交互问题
Bug: https://pms.uniontech.com/bug-view-167501.html
Influence: 清除按钮正常显示交互颜色
> fix: 修改消息中心清除按钮焦点策略和状态颜色

- dde-osd/notification/appbody.cpp
按UI要求，消息通知标题和内容间隔4像素
Log: 修复标题与内容间距问题
Bug: https://pms.uniontech.com/bug-view-167495.html
Influence: 消息通知标题和内容间隔4像素
> fix: 消息通知标题和内容间隔4像素

- dde-osd/notification-center/bubbleitem.cpp
设置消息内容自动扩展宽度
Log: 修复通知消息内容显示过短问题
Bug: https://pms.uniontech.com/bug-view-167487.html
Influence: 通知消息内容显示正常宽度
> fix: 设置消息内容自动扩展宽度

- dde-osd/osdprovider.cpp
OSD显示绘制图标时需要根据是否显示文字计算坐标偏移量
Log: 修复OSD显示wifi图标偏上的问题
Bug: https://pms.uniontech.com/bug-view-167449.html
Influence: OSD显示wifi图标居中
> fix: OSD显示绘制图标时需要根据是否显示文字计算坐标便宜量

- dde-osd/notification/actionbutton.cpp
- dde-osd/notification/actionbutton.h
在消息通知按钮的Text仅两个中文时插入空格
Log: 修复通知消息按钮文字间距问题
Bug: https://pms.uniontech.com/bug-view-167489.html
Influence: 消息通知按钮的Text仅两个中文时有空格
> fix: 在消息通知按钮的Text仅两个中文时插入空格

- dde-osd/notification/notifysettings.cpp
fix:  修复系统通知点击反应迟钝问题
由于用户安装了steam后，系统通知收到的消息ID为空，修改增加对消息ID为空的判断解决该问题
Log: 修复系统通知点击反应迟钝问题
Bug: https://pms.uniontech.com/bug-view-91059.html
Influence: 系统通知
> fix: 教育版合入专业版: 系统通知点击反应迟钝，大概率点不出来

- CMakeLists.txt
- common/CMakeLists.txt
- dde-bluetooth-dialog/src/CMakeLists.txt
- dde-bluetooth-dialog/tests/CMakeLists.txt
- dde-osd/CMakeLists.txt
- dde-osd/src/CMakeLists.txt
- dde-osd/tests/CMakeLists.txt
- dde-osd/tests/notification/ut_dockrect.cpp
- dde-suspend-dialog/src/CMakeLists.txt
- dde-suspend-dialog/tests/CMakeLists.txt
- dde-touchscreen-dialog/src/CMakeLists.txt
- dde-touchscreen-dialog/tests/CMakeLists.txt
- dde-welcome/CMakeLists.txt
- dde-welcome/src/CMakeLists.txt
- dde-welcome/tests/CMakeLists.txt
- dde-wm-chooser/src/CMakeLists.txt
- dde-wm-chooser/tests/CMakeLists.txt
- dmemory-warning-dialog/src/CMakeLists.txt
- dmemory-warning-dialog/tests/CMakeLists.txt
- global_util/CMakeLists.txt
- global_util/dbus/CMakeLists.txt
- reset-password-dialog/CMakeLists.txt
- widgets/CMakeLists.txt
避免将相同的源码添加到不同的子项目来减少不必要的构建，加快构建时间。并通过使用 GLOB 来使得 CMake 知道哪些源码需要重新进行构建，进一步简短再次构建时的构建时间。
> CMake: share code as object library, and avoid using glob

- .tx/config
- debian/changelog
* Avoid use GLOB for some subprojects (dde-osd, dde-welcome, etc)
* Reuse common utils as object libraries
* Ensure project source compliant with REUSE spec
* Fix dde-osd window round radius conflicting with blur effect
* Change the value of XDG_CURRENT_DESKTOP to DDE
> chore: bump version to 6.0.7

- dde-osd/src/notification/bubbletool.cpp
- dde-osd/src/notification/bubbletool.h
通过应用对应desktop文件启动应用
linuxdeepin/developer-center#3657
> fix(dde-osd): 修复玲珑应用通知无法跳转

- dde-osd/src/container.cpp
- dde-osd/src/notification/notifysettings.cpp
Log: fix when is id empty, osd break
这样就可以复现
```bash
gdbus call --session  \
--dest org.freedesktop.Notifications \
--object-path /org/freedesktop/Notifications \
--method org.freedesktop.Notifications.Notify \
"" \
42 \
"" \
"The Summary"\ 
"Here's the body of the notification" \ 
[] \
{} \
5000
```
> fix: when id is empty osd break, and wrong gsetting

- dde-osd/src/notification/bubbletool.cpp
- dde-osd/src/notification/bubbletool.h
该提交导致了其他问题，应用名称不一定是desktop文件的前缀，
需换另一种方式实现玲珑应用响应通知的场景。
> Revert "fix: 修复玲珑应用通知无法跳转"

- dde-pixmix/src/main.cpp
- dnetwork-secret-dialog/src/main.cpp
- dnetwork-secret-dialog/src/networkdialog.cpp
DLogManager's console has changed from std::cerr to std::out
in the commit 24a29a0f9f60a393e0b34f8b2b5d0ec9ea5bdcd1 , It will affect the interaction between dnetwork-secret-dialog and dde-session-daemon.
And the tool doesn't need ConsoleAppender for log.
Issue: https://github.com/linuxdeepin/developer-center/issues/5284
> fix: Can't update password for dnetwork-secret-dialog

- dde-osd/src/notification/bubblemanager.cpp
- dde-osd/src/notification/bubblemanager.h
- dde-osd/src/notification/bubbletool.h
- dde-osd/src/notification/notifications_dbus_adaptor.cpp
- dde-osd/src/notification/notifications_dbus_adaptor.h
- xml/org.deepin.dde.Notification1.xml
to split bubble function.
Issue: https://github.com/linuxdeepin/developer-center/issues/6095
> feat: support notification to switch other bubble

- reset-password-dialog/CMakeLists.txt
Append to CMAKE_EXE_LINKER_FLAGS instead of overwriting it.
> fix: don't override CMAKE_EXE_LINKER_FLAGS

- dde-osd/src/notification/notifysettings.cpp
Log: should split the objectpath first
> fix: coredump when uninstall app

- dde-osd/src/notification/bubblemanager.cpp
- dde-osd/src/notification/bubblemanager.h
- dde-osd/src/notification/notifications_dbus_adaptor.cpp
- dde-osd/src/notification/notifications_dbus_adaptor.h
- dde-osd/src/notification/persistence.cpp
- dde-osd/src/notification/persistence.h
- dde-osd/src/unittest.cpp
- dde-osd/tests/mockpersistence.h
- dde-osd/tests/notification-center/ut_notifyListview.cpp
- dde-osd/tests/notification-center/ut_notifycenterwidget.cpp
- dde-osd/tests/notification/ut_bubblemanager.cpp
Export RecordCount as a property and provide notify signal.
Log: add record count dbus property
> feat: add record count dbus property

- dde-osd/src/notification/bubblemanager.cpp
- dde-osd/src/notification/persistence.cpp
We add notification to Persistence for Replace Notification, and
wheather it emits RecordAdded signal depends on Bubble's notProcessedYet.
and emitting signal for replaced notification,
Issue: https://github.com/linuxdeepin/developer-center/issues/6930
> fix: missing notification for NotifyCenter

- dde-osd/src/notification/notifysettings.cpp
Only unconfigured applications have their notification settings reset to default values
Issue: https://github.com/linuxdeepin/developer-center/issues/7261
> fix: notification settings reset after restart

- dde-osd/src/notification/bubblemanager.cpp
- dde-osd/src/notification/notifysettings.cpp
- dde-osd/src/notification/notifysettings.h
- debian/changelog
- global_util/dbus/types/launcheriteminfo.cpp
- global_util/dbus/types/launcheriteminfo.h
chore: notify settings and icon tweak
- get appid from AM first(pid ==> appid)
- get appid from cached item info(.names)
- if icon is empty get icon from settings
- GenericName[lang] first then Name[lang]
- alwayays update icon and name in initAllSettings
linux.qq.com desktop 名是 qq.desktop 即 appID 是 qq ， 但是通知时 AppName 是QQ
Issue: https://github.com/linuxdeepin/developer-center/issues/8281
Issue: https://github.com/linuxdeepin/developer-center/issues/6907
b4:
now:
> chore: notify settings and icon tweak

- dnetwork-secret-dialog/src/main.cpp
- dnetwork-secret-dialog/src/networkdialog.cpp
- dnetwork-secret-dialog/src/networkdialog.h
Synchronize Professional Version Code
Issue: https://github.com/linuxdeepin/developer-center/issues/9726
> fix: Problem with password change pop-up not displaying

- dnetwork-secret-dialog/src/networksecretdialog.cpp
When initializing const global variables, the translation file has not been loaded yet, delaying the initialization of variables that need to be translated
Issue: https://github.com/linuxdeepin/developer-center/issues/10207
> fix: translation issue with networksecretdialog

- dde-pixmix/src/main.cpp
解决dde-pixmix在root下执行崩溃的问题
Issue: https://github.com/linuxdeepin/developer-center/issues/10310
> chore: 解决dde-pixmix在root下执行崩溃的问题

- dde-osd/src/notification-center/notifycenterwidget.cpp
as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9728
> fix: window removes its own display animation

- debian/control
log: add run Depends pandoc analysis .md file
Bug: https://pms.uniontech.com/bug-view-281497.html
> fix: add run Depends pandoc analysis .md file

- CMakeLists.txt
- dde-blackwidget/CMakeLists.txt
- dde-blackwidget/misc/dbus-services/org.deepin.dde.BlackScreen1.service
- dde-blackwidget/misc/systemd/user/dde-blackwidget.service
- dde-blackwidget/src/main.cpp
- dde-blackwidget/src/window.cpp
- dde-blackwidget/src/window.h
- dde-switchtogreeter/CMakeLists.txt
- debian/control
恢复丢失的 org.deepin.dde.BlackScreen 接口
Bug: https://pms.uniontech.com/bug-view-288277.html
> chore: add dde-blackscreen

- dde-license-dialog/src/content.cpp
- dde-license-dialog/src/mainwindow.h
- debian/control
> chore: remove the dependence of pandoc
