linuxdeepin/dde-session-ui

dde-shutdown/view/contentwidget.cpp
dde-shutdown/view/inhibitwarnview.cpp
dde-shutdown/view/inhibitwarnview.h

see: https://tower.im/teams/9487/todos/233102/

feat(shutdown): inhibitwarning support data sync

---

dde-session-ui.pro
dde-shutdown/view/contentwidget.cpp
files/dde-session-ui.conf.in
session-widgets/lockworker.cpp
session-widgets/sessionbasemodel.cpp
session-widgets/sessionbasemodel.h
widgets/shutdownwidget.cpp

新增配置文件选项来控制内部功能。
添加了arm上禁用休眠和睡眠的功能。

添加配置文件来替换编译宏控制

---

dde-lock/main.cpp
dde-shutdown/main.cpp
dde-shutdown/view/contentwidget.cpp
dde-shutdown/view/contentwidget.h
dde-shutdown/view/inhibitwarnview.cpp
global_util/multiscreenmanager.cpp
global_util/multiscreenmanager.h
lightdm-deepin-greeter/main.cpp

refactor(shutdown): use QStackedLayout replace QLayout

---

dde-shutdown/view/contentwidget.cpp
dde-shutdown/view/contentwidget.h

https://github.com/linuxdeepin/internal-discussion/issues/1184

optimize(shutdown): reduce the number of new object

---

dde-shutdown/app/shutdownframe.cpp
session-widgets/lockworker.cpp
session-widgets/lockworker.h

https://github.com/linuxdeepin/internal-discussion/issues/1193

fix: not check swap again

---

dde-session-ui.pro
files/dde-session-ui.conf.in
libdde-auth/authagent.cpp
libdde-auth/authagent.h
libdde-auth/authdbusadapter.cpp
libdde-auth/authdbusadapter.h
libdde-auth/dbus/com.deepin.daemon.Authority.xml
libdde-auth/dbus/com.deepin.daemon.authority.Agent.xml
libdde-auth/dbus/com.deepin.daemon.authority.Transaction.xml
libdde-auth/deepinauthframework.cpp
libdde-auth/deepinauthframework.h
libdde-auth/interface/deepinauthinterface.h
libdde-auth/libdde-auth.pri
session-widgets/lockworker.cpp
session-widgets/lockworker.h
session-widgets/session-widgets.pri

feat: support deepin-auth

---

lightdm-deepin-greeter/main.cpp

see: https://github.com/linuxdeepin/internal-discussion/issues/1231

feat(greeter): use new dpi scale ratio config

---

session-widgets/userinputwidget.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1426

fix(lock): not sync multi-screen user lock info

---

widgets/sessionwidget.cpp

see: https://github.com/linuxdeepin/internal-discussion/issues/1387

fix(greeter): session list position not align center

---

libdde-auth/deepinauthframework.cpp
libdde-auth/deepinauthframework.h
session-widgets/lockworker.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1504

fix(lock): not auth user when show again

---

dde-shutdown/view/inhibitwarnview.cpp
dde-shutdown/view/inhibitwarnview.h

https://github.com/linuxdeepin/internal-discussion/issues/1499

fix(shutdown): crash when show inhibitwarnview again

---

session-widgets/userinputwidget.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1507

fix(lock): No focus after closing login lock

---

widgets/sessionwidget.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1500

fix(greeter): not select user last use session

---

.github/PULL_REQUEST_TEMPLATE

Since we are now moving away from gerrit...

chore: remove pr template

---

dde-shutdown/view/multiuserswarningview.cpp

fix(shutdown): multiuser warning tips are truncated

---

dde-session-ui.pro
dde-shutdown/view/contentwidget.cpp
debian/control

cannot enter hover state
taskID=5506

fix(shutdown): when inhibitwarningview show after system monitor button

---

widgets/kblayoutwidget.cpp

fix(greeter): wrong set user keyboard layout

---

session-widgets/lockcontent.cpp

fix(lock): cannot reboot system

---

session-widgets/lockcontent.cpp

fix(greeter): missing blurdone signal

---

session-widgets/lockworker.cpp
session-widgets/userinfo.cpp
session-widgets/userinfo.h

fix(lock): when user unlock not reset checkpasswd num

---

session-widgets/sessionbasemodel.cpp

fix(greeter): update user list

---

dde-osd/common.cpp

fix (osd): allow word wrap in osd text.

---

libdde-auth/deepinauthframework.cpp
libdde-auth/deepinauthframework.h
session-widgets/lockworker.cpp

fix(lock): unlock when fake nopassword user

---

dde-shutdown/view/contentwidget.cpp
dde-shutdown/view/contentwidget.h
dde-shutdown/view/systemmonitor.cpp

fix (dde-shutdown): put system monitor button into a layout.

---

dde-shutdown/app/shutdownframe.cpp
dde-shutdown/app/shutdownframe.h
dde-shutdown/dbusshutdownagent.cpp
dde-shutdown/main.cpp
dde-shutdown/view/contentwidget.cpp
dde-shutdown/view/contentwidget.h
dde-shutdown/view/inhibitwarnview.cpp
dde-shutdown/view/inhibitwarnview.h
global_util/dbus/dbusvariant.cpp
global_util/dbus/dbusvariant.h

feat(dde-shutdown): support inhibit Suspend/Hibernate/Logout

---

dde-shutdown/view/contentwidget.cpp

Fix screen will light up when shutting down or restarting

fix(dde-shutdown): delay request reboot/shutdown

---

archlinux/PKGBUILD
archlinux/deepin-session-ui-qt5.15.patch
archlinux/fix-cmakelist.patch

add archlinux build

---

archlinux/PKGBUILD

fix: missing dtkcommon build dep

---

dde-switchtogreeter/switchtogreeter.c

原因：没有正常获取到session文件中的DISPLAY字段，导致切换用户失败。根因应该是systemd创建session文件的时候缺少了字段。 解决方案：从user文件中获取DISPLAY数据，如果在session中没有找到DISPLAY的，则使用user的DISPLAY。 可以使用DisplayManager服务提供的切换用户接口，有待测试。
Log: 解决切换用户异常的情况
Bug: https://pms.uniontech.com/bug-view-155487.html Influence:
Change-Id: I8d61e81dcb7cac7ef16c4a0a0d289494bdbf98fd

fix: 切换用户异常

---

translations/dde-session-ui_az.ts
translations/dde-session-ui_ca.ts
translations/dde-session-ui_cs.ts
translations/dde-session-ui_da.ts
translations/dde-session-ui_de.ts
translations/dde-session-ui_es.ts
translations/dde-session-ui_fi.ts
translations/dde-session-ui_it.ts
translations/dde-session-ui_pl.ts
translations/dde-session-ui_pt_BR.ts
translations/dde-session-ui_ru.ts
translations/dde-session-ui_sl.ts
translations/dde-session-ui_sr.ts
translations/dde-session-ui_tr.ts
translations/dde-session-ui_ug.ts
translations/toggle-desktop/desktop.ts

更新翻译
Log: 更新翻译
Task: https://pms.uniontech.com/task-view-202033.html
Influence: 翻译
Change-Id: Iec0ea31bd274dc5d11e6a824906ede394da26a1c

chore: 更新翻译

---

CMakeLists.txt
dnetwork-secret-dialog/networkdialog.cpp
dnetwork-secret-dialog/networkdialog.h

网络后端与网络面板通讯改用QLocalSocket通讯
Log: 修复锁屏可通过快捷键切入桌面问题
Bug: https://pms.uniontech.com/bug-view-151907.html,https://pms.uniontech.com/bug-view-147677.html
Influence: 无线密码错误自动弹窗

fix: 修改dnetwork-secret-dialog与网络面板通讯方式

---

.tx/deepin.conf
debian/changelog

update changelog to 5.6.2
Log: update changelog to 5.6.2
Influence: 构建
Change-Id: If926288c9751610380d02c97509d46b80c9f0c9a

chore: update changelog to 5.6.2

---

dde-osd/src/container.cpp
dde-osd/src/container.h

There is a conflict between the window rounding effect and the blur effect.
Closed https://github.com/linuxdeepin/developer-center/issues/3718
Closed https://github.com/linuxdeepin/developer-center/issues/3602

fix: window radius

---

dde-osd/src/main.cpp
dde-warning-dialog/src/main.cpp
reset-password-dialog/main.cpp

Change XDG_CURRENT_DESKTOP to DDE.

fix: change XDG_CURRENT_DESKTOP to DDE

---

archlinux/PKGBUILD

chore(CI): correct conflicts depends and correct source name

---

.gitignore
CMakeLists.txt
dde-osd/src/common.cpp

fix: compile failed after dtkwidget upgrade

---

debian/changelog

chore: Update changelog to 6.0.10

---

dde-osd/src/notification/notifysettings.cpp

The interface has removed in AM.
Only fetch once and use async way.

fix: repeated warning when fetch GetAllItemInfos

---

dde-osd/src/notification/bubble.cpp
dde-osd/src/notification/bubble.h
dde-osd/src/notification/bubblemanager.cpp
dde-osd/src/notification/bubblemanager.h
dde-osd/src/notification/notificationentity.cpp
dde-osd/src/notification/notificationentity.h
dde-osd/src/notification/persistence.cpp
dde-osd/src/notification/persistence.h

store a notification to database immediately when it pops up. remove notification from database when it is processed.
Log: Store a notification to database immediately when it pops up

chore: Store a notification to database immediately when it pops up

---

debian/changelog

chore: update changelog to 6.0.11

---

dde-osd/src/notification/bubblemanager.cpp

We can check ut by `calledFromDBus` instead of `GTEST` macro.

fix: ut crashed when calling DBusContext method

---

dde-osd/src/notification/bubblemanager.cpp

We only support external bubble in treeland.
Using `DDE_CURRENT_COMPOSITER=TreeLand` to check whether is treeland.
Issue: https://github.com/linuxdeepin/developer-center/issues/6095

fix: dde-osd can't display bubble in treeland

---

debian/changelog

chore: update changelog to 6.0.12

---

dde-license-dialog/src/content.cpp
dde-license-dialog/src/mainwindow.cpp
dde-lowpower/src/window.cpp
dde-lowpower/src/window.h
dde-osd/src/common.cpp
dde-osd/src/kblayoutprovider.cpp
dde-osd/src/notification-center/notifylistview.cpp
dde-osd/src/notification/actionbutton.cpp
dde-osd/src/notification/bubbletool.cpp
dde-osd/src/notification/bubbletool.h
dde-osd/src/notification/icondata.cpp
dde-touchscreen-dialog/src/recognizedialog.cpp
dde-welcome/src/updatecontent.cpp
reset-password-dialog/resetpassworddialog.cpp

Log: remove all compile warning

chore: remove the warning during compiling

---

CMakeLists.txt
dde-bluetooth-dialog/src/CMakeLists.txt
dde-hints-dialog/src/CMakeLists.txt
dde-license-dialog/src/CMakeLists.txt
dde-lowpower/src/CMakeLists.txt
dde-osd/src/CMakeLists.txt
dde-pixmix/src/CMakeLists.txt
dde-suspend-dialog/src/CMakeLists.txt
dde-switchtogreeter/src/CMakeLists.txt
dde-touchscreen-dialog/src/CMakeLists.txt
dde-warning-dialog/src/CMakeLists.txt
dde-welcome/src/CMakeLists.txt
dde-wm-chooser/src/CMakeLists.txt
dnetwork-secret-dialog/src/CMakeLists.txt
reset-password-dialog/CMakeLists.txt
reset-password-dialog/main.cpp

not install reset-password-dialog, it is not used anymore, and delete it, for it is only only for uos
use GNUInstallDirs
Log:

chore: tidyup project

---

dde-osd/src/notification/notifysettings.cpp

fix: nodisplay desktop is added to notifysettings

---

dde-license-dialog/src/content.cpp
debian/control

chore: remove the dependence of pandoc

---

dde-osd/src/notification/notifysettings.cpp

chore: fix typo

---

dde-osd/src/notification/bubblemanager.cpp
debian/changelog

chore: bump version to 6.0.15

---

debian/changelog

chore: update changelog to 6.0.16

---

dde-osd/src/notification/bubblemanager.cpp

wrong position of notification in 4k screen
Issue: https://github.com/linuxdeepin/developer-center/issues/8026

fix: wrong position of notification

---

dde-osd/src/notification/notifysettings.cpp
dde-osd/src/notification/persistence.cpp

1. fix: notification record count could be -1 [https://bbs.deepin.org.cn/zh/post/273222](https://bbs.deepin.org.cn/zh/post/273222)
2. fix: incorrect X-Deepin-Vendor check for LauncherItemInfo

fix: incorrect record count and app name

---

dde-osd/src/osdprovider.cpp

Issues: linuxdeepin/developer-center#8899

fix: the text not being vertically centered

---

debian/changelog

release 6.0.20
Log: bump version to 6.0.20

chore: bump version to 6.0.20

---

debian/changelog

bump version to 6.0.22
Log: bump version to 6.0.22

chchore: bump version to 6.0.22

---

dde-license-dialog/src/content.cpp

Log: Adapt user experience plan agreement md format document
Bug: https://pms.uniontech.com/bug-view-281497.html

fix: Adapt user experience plan agreement md format document

---

debian/changelog

chore: bump to 6.0.23

---

debian/changelog

chore: bump to 6.0.24

---

dde-blackwidget/src/main.cpp

fix: accessing log when app is destroyed

---

debian/changelog

chore: bump version to 6.0.26 update changelog
